import type { Metadata } from "next";
import { Inter, Jost, Kanit, Mukta } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const mukta = Kanit({
  weight: ["400", "300", "600", "700", "800"],
  variable: "--font-mukta",
  subsets: ["latin"]
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${mukta.variable}`}>{children}</body>
    </html>
  );
}
